// constants.js

export const Strings = {
  signupTitle: 'Signup to your Account',
  firstNameLabel: 'First Name',
  lastNameLabel: 'Last Name',
  phoneNumberLabel: 'Phone Number',
  emailLabel: 'Email ID',
  addressLabel: 'Address',
  firmNameLabel: 'Firm Name',
  gstinLabel: 'GSTIN No.',
  passwordLabel: 'Password',
  privacyPolicyError: 'You must accept the Privacy Policy to continue.',
  confirmPasswordLabel: 'Confirm Password',
  signupButton: 'Signup',
  emailError: 'Please enter a valid email address',
  phoneError: 'Please enter a valid 10-digit phone number',
  passwordError: 'Password must be at least 8 characters long, contain at least one special character, and contain at least two numbers',
  confirmPasswordError: 'Passwords do not match',
  signupSuccess: 'Signup successful',
  signupError: 'Error',
  signupFailure: 'Failed to signup. Please try again later.',
  termsAndConditionsTitle: 'Terms and Conditions for Event Planner App',
  introductionTitle: '1. Introduction',
  introductionText: 'Welcome to [App Name]! These Terms and Conditions govern your use of our event planner app. By downloading or using the app, you agree to comply with these terms. Please read them carefully.',
  accountRegistrationTitle: '2. Account Registration and Use',
  accountRegistrationText: 'To access certain features of the app, you must create an account. You agree to provide accurate and complete information during registration and to keep this information up to date. You are responsible for maintaining the confidentiality of your account and password.',
  userConductTitle: '3. User Conduct and Responsibilities',
  userConductText: 'Users agree to use the app only for lawful purposes and in a way that does not infringe the rights of, restrict, or inhibit anyone else\'s use and enjoyment of the app. Users are responsible for any content they post and must ensure it is not illegal, defamatory, or infringing on others\' rights.',
  eventManagementTitle: '4. Event Creation and Management',
  eventManagementText: 'When creating events, you agree to provide accurate information and to update this information as necessary. You are solely responsible for managing attendees and ensuring all communications comply with applicable laws and regulations.',
  privacyProtectionTitle: '5. Privacy and Data Protection',
  privacyProtectionText: 'We are committed to protecting your privacy. Please review our Privacy Policy to understand how we collect, use, and protect your personal information.',
  closeButtonText: 'Close',
};

export const SIGNUP_API_ENDPOINT = '/auth/create_user';
